DROP TABLE IF EXISTS MEMBER CASCADE;
CREATE TABLE MEMBER (
    `MEMBER_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `MEMBER_ID`		VARCHAR(16) NOT NULL COMMENT '회원 아이디',
    `MEMBER_NAME`	VARCHAR(16) NOT NULL COMMENT '회원 이름',
    `MEMBER_STATUS`	VARCHAR(16) NOT NULL COMMENT '회원 상태',
    `CREATED_AT`	DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`	DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`MEMBER_NO`)
);
CREATE UNIQUE INDEX `MEMBER_MEMBER_ID_IDX1` ON MEMBER (`MEMBER_ID`);

DROP TABLE IF EXISTS BILL CASCADE;
CREATE TABLE BILL (
    `BILL_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `MEMBER_NO`		BIGINT NOT NULL COMMENT '회원번호',
    `BILL_STATUS`	VARCHAR(16) NOT NULL COMMENT '결제상태',
    `BILL_TYPE`		VARCHAR(16) NOT NULL COMMENT '결제유형',
    `TOTAL_AMOUNT`	INTEGER NOT NULL COMMENT '총결제금액',
    `CREATED_AT`	DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`	DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`BILL_NO`)
);
CREATE INDEX `BILL_MEMBER_NO_IDX1` ON BILL (`MEMBER_NO`);

DROP TABLE IF EXISTS ORDERS CASCADE;
CREATE TABLE ORDERS (
    `ORDER_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `BILL_NO`		BIGINT NOT NULL COMMENT '결제번호',
    `GOODS_NO`		BIGINT NOT NULL COMMENT '상품번호',
    `GOODS_PRICE`	INTEGER NOT NULL COMMENT '결제시점 상품금액',
    `ORDER_CNT`		INTEGER NOT NULL COMMENT '주문건수',
    `CREATED_AT`	DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`	DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`ORDER_NO`)
);
CREATE INDEX `ORDERS_BILL_NO_IDX1` ON ORDERS (`BILL_NO`);

DROP TABLE IF EXISTS GOODS CASCADE;
CREATE TABLE GOODS (
    `GOODS_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `BRAND_NO`		BIGINT NOT NULL COMMENT '브랜드번호',
    `GOODS_NAME`	VARCHAR(128) NOT NULL COMMENT '상품명',
    `GOODS_PRICE`	INTEGER NOT NULL COMMENT '상품금액',
    `SALE_PRICE`	INTEGER NOT NULL COMMENT '할인금액',
    `DISPLAY_YN`	CHAR(1) NOT NULL COMMENT '노출여부',
    `CREATED_AT`	DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`	DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`GOODS_NO`)
);
CREATE INDEX `BRAND_BRAND_NO_IDX1` ON GOODS (`BRAND_NO`);

DROP TABLE IF EXISTS BRAND CASCADE;
CREATE TABLE BRAND (
    `BRAND_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `BRAND_NAME`	VARCHAR(128) NOT NULL COMMENT '브랜드명',
    `DISPLAY_YN`	CHAR(1) NOT NULL COMMENT '노출여부',
    `CREATED_AT`	DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`	DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`BRAND_NO`)
);

DROP TABLE IF EXISTS DELIVERY CASCADE;
CREATE TABLE DELIVERY (
    `DELIVERY_NO`		BIGINT NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `BILL_NO`			BIGINT NOT NULL COMMENT '결제번호',
    `DELIVERY_STATUS`	VARCHAR(16) NOT NULL COMMENT '배송상태',
    `ZIPCODE`			VARCHAR(16) NOT NULL COMMENT '우편번호',
    `CITY`				VARCHAR(255) NOT NULL COMMENT '주소',
    `STREET`			VARCHAR(255) NOT NULL COMMENT '상세주소',
    `CREATED_AT`		DATETIME NOT NULL COMMENT '등록일시',
    `MODIFIED_AT`		DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY(`DELIVERY_NO`)
);
CREATE INDEX `DELIVERY_BILL_NO_IDX1` ON DELIVERY (`BILL_NO`);
